import { NextRequest, NextResponse } from 'next/server';
import Anthropic from '@anthropic-ai/sdk';

const client = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });

export async function POST(req: NextRequest) {
  try {
      const { image, mimeType, jobId, itemId } = await req.json();

          if (!image) {
                return NextResponse.json({ error: 'No image provided' }, { status: 400 });
                    }

                        const response = await client.messages.create({
                              model: 'claude-opus-4-5',
                                    max_tokens: 256,
                                          messages: [
                                                  {
                                                            role: 'user',
                                                                      content: [
                                                                                  {
                                                                                                type: 'image',
                                                                                                              source: {
                                                                                                                              type: 'base64',
                                                                                                                                              media_type: (mimeType || 'image/jpeg') as 'image/jpeg' | 'image/png' | 'image/gif' | 'image/webp',
                                                                                                                                                              data: image,
                                                                                                                                                                            },
                                                                                                                                                                                        },
                                                                                                                                                                                                    {
                                                                                                                                                                                                                  type: 'text',
                                                                                                                                                                                                                                text: 'Look at this appliance serial number tag. Extract ONLY the serial number. Return just the serial number with no extra text, labels, or explanation. If you cannot find a serial number, return the word NOTFOUND.',
                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                      ],
                                                                                                                                                                                                                                                              },
                                                                                                                                                                                                                                                                    ],
                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                            const serial = (response.content[0] as { type: string; text: string }).text.trim();
                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                if (serial === 'NOTFOUND' || !serial) {
                                                                                                                                                                                                                                                                                      return NextResponse.json({ error: 'Could not read serial number from image' });
                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                              // If Google Apps Script URL is set, forward the serial back
                                                                                                                                                                                                                                                                                                  let saved = false;
                                                                                                                                                                                                                                                                                                      const scriptUrl = process.env.APPS_SCRIPT_URL;
                                                                                                                                                                                                                                                                                                          if (scriptUrl && jobId && itemId) {
                                                                                                                                                                                                                                                                                                                try {
                                                                                                                                                                                                                                                                                                                        await fetch(scriptUrl, {
                                                                                                                                                                                                                                                                                                                                  method: 'POST',
                                                                                                                                                                                                                                                                                                                                            headers: { 'Content-Type': 'application/json' },
                                                                                                                                                                                                                                                                                                                                                      body: JSON.stringify({ action: 'saveSerial', jobId, itemId, serial }),
                                                                                                                                                                                                                                                                                                                                                              });
                                                                                                                                                                                                                                                                                                                                                                      saved = true;
                                                                                                                                                                                                                                                                                                                                                                            } catch {
                                                                                                                                                                                                                                                                                                                                                                                    // non-fatal
                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                  return NextResponse.json({ serial, saved });
                                                                                                                                                                                                                                                                                                                                                                                                    } catch (err: unknown) {
                                                                                                                                                                                                                                                                                                                                                                                                        const message = err instanceof Error ? err.message : 'Unknown error';
                                                                                                                                                                                                                                                                                                                                                                                                            return NextResponse.json({ error: message }, { status: 500 });
                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                              }
